config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'about' => 'home#about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get :quit
      patch :cancel
      get :following
      get :followers
      get :learnings
      get :stocks
    end
    resource :relationships, only: [:create, :destroy]
    resources :notifications, only: :index do
      delete :destroy_all, on: :collection
    end
  end

  resources :apps, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      post :confirm
      get :rate_index
      get :popular_index
      get :tag
      get :rate_tag
      get :popular_tag
    end
    member do
      get :hint
      get :explanation
      get :hint_edit
      get :explanation_edit
      patch :add_update
      get :hidden
      patch :cancel
    end
    resources :learnings, only: [:create, :show, :edit, :update]
    resources :questions, only: [:index, :create]
    resources :reviews, only: [:index, :create]
    resource :stocks, only: [:create, :destroy]
  end

  resources :langs, only: :show do
    member do
      get :rate_show
      get :popular_show
    end
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    post 'admin/guest_sign_in' => 'admins/sessions#new_guest'
  end

  namespace :admin do
    root 'dashboards#index'
    resources :langs, only: [:index, :show, :create, :update, :destroy]
    resources :users, only: :index do
      patch :cancel, on: :member
    end
    resources :apps, only: :index do
      patch :cancel, on: :member
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"

  def create_notification_follow!(current_user, follower_id)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, follower_id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: follower_id,
        action: "follow"
      )
      notification.save
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @follow = User.find(params[:user_id]) # クリックされたフォローされるアカウントを取得
    @user = User.find(params[:user_now])
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    follow.create_notification_follow!(current_user, follow.follower_id)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @follow = User.find(params[:user_id])
    @user = User.find(params[:user_now])
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/views/relationships/_follow_count.html.slim
li#following
  = link_to "フォロー数 #{user.followings.count}人", following_user_path(user), class: "btn-original3"
li#followers
  = link_to "フォロワー数 #{user.followers.count}人", followers_user_path(user), class: "btn-original3"

app/views/relationships/_follow_form.html.slim
- if current_user.following?(user)
  =link_to "フォロー中", user_relationships_path(user, {:user_now => @user.id}), method: :delete, remote: true, class: "btn btn-sm btn-primary"
- else
  =link_to "フォローする", user_relationships_path(user, {:user_now => @user.id}), method: :post, remote: true, class: "btn btn-sm btn-default"

app/views/relationships/create.js.slim
| $("#follow-form-
= @follow.id
| ").html("
= j(render 'relationships/follow_form', user: @follow)
| "); $("#user-follow").html("
= j(render 'relationships/follow_count', user: @user)
| "); $("#follow-count").html("
= j(render 'relationships/follow_count', user: @user)
| ");

app/views/relationships/destroy.js.slim
| $("#follow-form-
= @follow.id
| ").html("
= j(render 'relationships/follow_form', user: @follow)
| "); $("#user-follow").html("
= j(render 'relationships/follow_count', user: @user)
| "); $("#follow-count").html("
= j(render 'relationships/follow_count', user: @user)
| ");