config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'about' => 'home#about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get :quit
      patch :cancel
      get :following
      get :followers
      get :learnings
      get :stocks
    end
    resource :relationships, only: [:create, :destroy]
    resources :notifications, only: :index do
      delete :destroy_all, on: :collection
    end
  end

  resources :apps, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      post :confirm
      get :rate_index
      get :popular_index
      get :tag
      get :rate_tag
      get :popular_tag
    end
    member do
      get :hint
      get :explanation
      get :hint_edit
      get :explanation_edit
      patch :add_update
      get :hidden
      patch :cancel
    end
    resources :learnings, only: [:create, :show, :edit, :update]
    resources :questions, only: [:index, :create]
    resources :reviews, only: [:index, :create]
    resource :stocks, only: [:create, :destroy]
  end

  resources :langs, only: :show do
    member do
      get :rate_show
      get :popular_show
    end
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    post 'admin/guest_sign_in' => 'admins/sessions#new_guest'
  end

  namespace :admin do
    root 'dashboards#index'
    resources :langs, only: [:index, :show, :create, :update, :destroy]
    resources :users, only: :index do
      patch :cancel, on: :member
    end
    resources :apps, only: :index do
      patch :cancel, on: :member
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(google_oauth2)
  attachment :profile_image

  has_many :apps
  has_many :learnings, dependent: :destroy
  has_many :questions
  has_many :reviews
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following
  has_many :active_notifications, class_name: "Notification", foreign_key: :visitor_id, dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: :visited_id, dependent: :destroy
  has_many :stocks, dependent: :destroy

  validates :name, presence: true, length: { maximum: 30 }
  validates :status, inclusion: { in: [true, false] }

  def active_for_authentication?
    super && (status == true)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.guest
    find_or_create_by!(name: "ゲストユーザー", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.admin
    find_or_create_by!(name: "管理者", email: "admin@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first
    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        name: auth.info.name,
        email: auth.info.email,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    { user: user, sns: sns }
  end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    if user.blank?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email,
      )
    end
    { user: user }
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    { user: user, sns: sns }
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @user_q = User.ransack(params[:q])
    @users = @user_q.result(distinct: true).page(params[:page]).per(10)
  end

  def cancel
    @user = User.find(params[:id])
    @user.update(status: false)
    flash[:success] = "指定のユーザーを退会させました。"
    redirect_back(fallback_location: admin_root_path)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "devise/registrations/new"
    end
  end

  def failure
    redirect_to(root_path) && return
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to apps_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :ensure_correct_user, only: [:learnings, :stocks, :edit, :update, :quit, :cancel]

  def set_user
    @user = User.find(params[:id])
  end

  def show
    @post_apps = @user.apps.includes(:lang, :reviews, :taggings)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました。"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def quit
  end

  def cancel
    @user.update(status: false)
    flash[:alert] = "アカウントを削除しました。"
    redirect_to root_path
  end

  def following
    @users = @user.followings.order(created_at: :desc)
  end

  def followers
    @users = @user.followers.order(created_at: :desc)
  end

  def learnings
    @learnings = @user.learnings.includes({ :app => :lang }, { :app => :reviews }, { :app => :taggings })
  end

  def stocks
    @stocks = @user.stocks.includes({ :app => :lang }, { :app => :reviews }, { :app => :taggings })
  end

  def ensure_correct_user
    if @user != current_user && !admin_signed_in?
      flash[:alert] = "アクセス権限がありません。"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction, :skill)
  end
end

app/views/users/_user_app_index.html.slim
h4
  = link_to app.title, app_path(app)
= render 'reviews/average_rate', app: app
p
  | 開発言語：
  = link_to app.lang.name, lang_path(app.lang)
.tag-lists
  - app.tag_list.each do |tag|
    span.tag-link
      = link_to tag, tag_apps_path(tag_name: tag), class: "btn-xs btn-default btn-tag"

app/views/users/_user_index.html.slim
- users.each do |user|
  .user-box
    .follow-user-img
      = link_to user_path(user) do
        = attachment_image_tag(user, :profile_image, size: "60x60", format: "jpeg", fallback: "no_image.jpg", class: "img-circle")
    .follow-user-info
      h4
        = user.name
      - if current_user != user
        |  <span id="follow-form-
        = user.id
        | "> 
        = render 'relationships/follow_form', user: user
      p
        = user.introduction
      p
        = user.skill

app/views/users/_user_info.html.slim
.row.user-edit
  #user-image.col-sm-3.col-sm-offset-1
    = attachment_image_tag(user, :profile_image, size: "150x150", format: "jpeg", fallback: "no_image.jpg", class: "img-circle")
  #user-info.col-sm-7
    #user-acount
      h3
        = user.name
      - if user == current_user
        = link_to "アカウント情報を編集", edit_user_path(user), class: "btn btn-default"
      - else
        |  <span id="follow-form-
        = user.id
        | "> 
        = render 'relationships/follow_form', user: user
    ul#user-follow
      = render 'relationships/follow_count', user: user
    #user-introduction
      h4
        | 自己紹介
      = user.introduction
    #user-skill
      h4
        | 学習スキル
      = user.skill

app/views/users/_user_sidebar.html.slim
- if user_signed_in?
  #my-info-bar
    = link_to user_path(user), id: "my-img" do
      #my-name
        = attachment_image_tag(user, :profile_image, size: "60x60", format: "jpeg", fallback: "no_image.jpg", class: "img-circle")
        span
          = user.name
    hr
    #my-app
      - if user == current_user
        h4
          | マイアプリ
      - else
        h4
          | アプリ情報
      ul#app-count
        li
          = link_to "投稿 #{user.apps.count}件", user_path(user), class: "btn-original3"
        li
          = link_to "学習 #{user.learnings.count}件", learnings_user_path(user), class: "btn-original3"
        li#stock-count-btn
          = render 'stocks/stock_count_btn', user: user
    hr
    #my-user
      - if user == current_user
        h4
          | マイユーザー
      - else
        h4
          | ユーザー情報
      ul#follow-count
        = render 'relationships/follow_count', user: user

app/views/users/edit.html.slim
.container
  .row.border-box
    .col-md-3.border-space
      ul.edit-link
        li
          | プロフィール編集
        li
          = link_to "パスワード変更", edit_user_registration_path
        li
          = link_to "アカウント停止", quit_user_path(@user)
    .col-md-9.border-left.border-space
      .row
        .col-md-10.col-md-offset-1
          = form_with(model: @user, local: true) do |f|
            .field.edit-user
              = attachment_image_tag(@user, :profile_image, size: "150x150", format: "jpeg", fallback: "no_image.jpg", class: "img-circle", id: "imagePreview")
              .edit-user-name
                h3
                  = @user.name
                = f.attachment_field :profile_image, id: "image"
            .edit-user-form
              = render 'layouts/error_messages', model: @user
              .field.user-form
                = f.label :name, "ユーザーネーム"
                = f.text_field :name, class: "form-control"
              .field.user-form
                = f.label :email, "メールアドレス"
                = f.email_field :email, class: "form-control"
              .field.user-form
                = f.label :introduction, "自己紹介"
                = f.text_area :introduction, class: "form-control"
              .field.user-form
                = f.label :skill, "学習スキル"
                = f.text_area :skill, class: "form-control"
              .actions.text-center
                = f.submit "更新する", class: "btn btn-original"

app/views/users/followers.html.slim
.container
  .row
    .col-sm-3.sidebar.fixed
      = render 'users/user_sidebar', user: @user
    .col-sm-9
      .user-index.back-white
        ul.nav.nav-tabs
          li
            = link_to "フォロー中", following_user_path(@user)
          li.active
            = link_to "フォロワー", followers_user_path(@user)
        - if @users.present?
          = render 'user_index', users: @users
        - else
          p
            | フォロワーはいません。

app/views/users/following.html.slim
.container
  .row
    .col-sm-3.sidebar.fixed
      = render 'users/user_sidebar', user: @user
    .col-sm-9
      .user-index.back-white
        ul.nav.nav-tabs
          li.active
            = link_to "フォロー中", following_user_path(@user)
          li
            = link_to "フォロワー", followers_user_path(@user)
        - if @users.present?
          = render 'user_index', users: @users
        - else
          p
            | フォローしているユーザーはいません。

app/views/users/followings.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3 sidebar">
      <%= render 'users/user_sidebar', user: @user %>
    </div>

    <div class="col-sm-9">
      <div class="user-index back-white">
        <ul class="nav nav-tabs">
          <li class="active"><%= link_to "フォロー中", followings_user_path(@user) %></li>
          <li><%= link_to "フォロワー", followers_user_path(@user) %></li>
        </ul>
        <% if @users.present? %>
          <%= render 'user_index', users: @users %>
        <% else %>
          <p>フォローしているユーザーはいません。</p>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/users/learnings.html.slim
.container
  - if @user.status == true
    = render 'user_info', user: @user
    .row.back-white
      #user-app
        ul.user-app-menu.nav.nav-tabs
          li
            = link_to "投稿#{@user.apps.count}件", user_path(@user)
          li.active
            = link_to "学習#{@user.learnings.count}件", learnings_user_path(@user)
          li
            = link_to "ストック#{@user. stocks.count}件", stocks_user_path(@user)
        #user-app-contents
          - if @learnings.present?
            - @learnings.each do |learning|
              .my-app-box
                .row
                  .my-app.col-md-9
                    = render 'user_app_index', app: learning.app
                  .my-learning-status.col-md-3
                    p
                      | 学習開始日： 
                      = learning.created_at.strftime("%Y年%m月%d日")
                    p
                      | 学習状況： 
                      = learning.status
                    - if learning.status == "学習済み"
                      - if Review.find_by(user_id: @user.id, app_id: learning.app.id).present?
                        p
                          | レビュー済み
                      - else
                        - if admin_signed_in?
                          p
                            | レビュー未投稿
                        - else
                          = link_to "レビューを投稿する", app_reviews_path(learning.app), class: "btn btn-primary"
          - else
            h4
              | 学習中・学習済みのアプリケーションはありません。
  - else
    h4
      | 退会済みのユーザーです。

app/views/users/quit.html.slim
.container
  .row.border-box
    .col-md-3.border-space
      ul.edit-link
        li
          = link_to "プロフィール編集", edit_user_path(@user)
        li
          = link_to "パスワード変更", edit_user_registration_path
        li
          | アカウント停止
    .col-md-9.border-left.border-space
      .row
        .col-md-10.col-md-offset-1
          .edit-user
            = attachment_image_tag(@user, :profile_image, size: "150x150", format: "jpeg", fallback: "no_image.jpg", class: "img-circle")
            h3.edit-user-name
              = @user.name
          .confirm-message
            p
              | 現在利用しているアカウントを停止（退会）します。
              br
              | 退会すると、これまで利用された学習履歴やマイページが
              br
              | 全て閲覧できなくなります。
              br
              br
              | 本当に退会してもよろしいですか？
            = link_to "アカウントを継続", user_path(@user), class: "btn btn-primary"
            = link_to "退会する", cancel_user_path(@user), method: :patch, class: "btn btn-danger", "data-confirm" => "退会してもよろしいですか？"

app/views/users/show.html.slim
.container
  - if @user.status == true
    = render 'user_info', user: @user
    .row.back-white
      #user-app
        ul.user-app-menu.nav.nav-tabs
          li.active
            = link_to "投稿#{@user.apps.count}件", user_path(@user)
          li
            = link_to "学習#{@user.learnings.count}件", learnings_user_path(@user)
          li
            = link_to "ストック#{@user. stocks.count}件", stocks_user_path(@user)
        #user-app-contents
          - if @post_apps.present?
            - @post_apps.each do |app|
              .my-app-box
                .row
                  .my-app.col-md-10
                    = render 'user_app_index', app: app
                  - if @user == current_user
                    .my-app-edit.col-md-2
                      - if app.status == true
                        = link_to "内容を編集する", edit_app_path(app), class: "btn btn-primary"
                      - else
                        p.btn-danger
                          | 非公開済みのアプリです
          - else
            h4
              | 投稿したアプリケーションはありません。
  - else
    h4
      | 退会済みのユーザーです。

app/views/users/stocks.html.slim
.container
  - if @user.status == true
    = render 'user_info', user: @user
    .row.back-white
      #user-app
        ul.user-app-menu.nav.nav-tabs
          li
            = link_to "投稿#{@user.apps.count}件", user_path(@user)
          li
            = link_to "学習#{@user.learnings.count}件", learnings_user_path(@user)
          li#stock-count.active
            = render 'stocks/stock_count', user: @user
        #user-app-contents
          - if @stocks.present?
            - @stocks.each do |stock|
              .my-app-box
                .row
                  .my-app.col-md-9
                    = render 'user_app_index', app: stock.app
                  .col-md-3
                    |  <span class="stock-button" id="stock-form-
                    = stock.app_id
                    | "> 
                    = render 'stocks/stock_form', app: stock.app
          - else
            h4
              | ストック中のアプリケーションはありません。
  - else
    h4
      | 退会済みのユーザーです。