config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'about' => 'home#about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get :quit
      patch :cancel
      get :following
      get :followers
      get :learnings
      get :stocks
    end
    resource :relationships, only: [:create, :destroy]
    resources :notifications, only: :index do
      delete :destroy_all, on: :collection
    end
  end

  resources :apps, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      post :confirm
      get :rate_index
      get :popular_index
      get :tag
      get :rate_tag
      get :popular_tag
    end
    member do
      get :hint
      get :explanation
      get :hint_edit
      get :explanation_edit
      patch :add_update
      get :hidden
      patch :cancel
    end
    resources :learnings, only: [:create, :show, :edit, :update]
    resources :questions, only: [:index, :create]
    resources :reviews, only: [:index, :create]
    resource :stocks, only: [:create, :destroy]
  end

  resources :langs, only: :show do
    member do
      get :rate_show
      get :popular_show
    end
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    post 'admin/guest_sign_in' => 'admins/sessions#new_guest'
  end

  namespace :admin do
    root 'dashboards#index'
    resources :langs, only: [:index, :show, :create, :update, :destroy]
    resources :users, only: :index do
      patch :cancel, on: :member
    end
    resources :apps, only: :index do
      patch :cancel, on: :member
    end
  end
end

app/views/apps/_app_index.html.slim
- if apps.present?
  - apps.each do |app|
    .link-app-box
      .link-app-user
        = link_to user_path(app.user) do
          = attachment_image_tag(app.user, :profile_image, size: "60x60", format: "jpeg", fallback: "no_image.jpg", class: "img-circle")
      .link-app-info
        |  <span class="stock-button" id="stock-form-
        = app.id
        | "> 
        - if user_signed_in?
          = render 'stocks/stock_form', app: app
        - else
          i.fas.fa-folder.fa-2x
        h4
          = link_to app.title, app_path(app)
        = render 'reviews/average_rate', app: app
        span.learning-count
          | 学習者：
          = app.learnings.count
          | 人
        p
          | 開発言語：
          = link_to app.lang.name, lang_path(app.lang)
        - app.tag_list.each do |tag|
          span.tag-link
            = link_to tag, tag_apps_path(tag_name: tag), class: "btn-xs btn-default btn-tag"
  .paginate
    = paginate apps
- else
  p
    | 検索に該当するアプリがありません。

app/views/apps/_app_info_top.html.slim
section.app-info-top
  .app-post
    = link_to user_path(app.user) do
      = attachment_image_tag(app.user, :profile_image, size: "40x40", format: "jpeg", fallback: "no_image.jpg", class: "img-circle")
    span
      = app.user.name
    span
      = app.updated_at.strftime("%Y年%m月%d日更新")
  |  <span class="stock-button" id="stock-form-
  = app.id
  | "> 
  - if user_signed_in?
    = render 'stocks/stock_form', app: app
  - else
    i.fas.fa-folder.fa-2x
  h1
    = app.title
  #average-rate
    = render 'reviews/average_rate', app: @app
  p
    | 開発言語：
    = link_to app.lang.name, lang_path(app.lang)
  - app.tag_list.each do |tag|
    span.tag-link
      = link_to tag, tag_apps_path(tag_name: tag), class: "btn-xs btn-default btn-tag"

app/views/apps/_tag_index.html.slim
ul#tag-index
  - ActsAsTaggableOn::Tag.most_used(30).each do |tag|
    li.tag-link.current-tag
      = link_to  "#{tag}（#{tag.taggings_count}）", tag_apps_path(tag_name: tag.name), class: "btn-xs btn-default btn-tag"

app/views/apps/explanation.html.slim
.container
  .row
    .col-sm-10
      .app-show-box.border-space
        #app-explanation
          = render 'learnings/learning_status', app: @app, learning: @learning
          #explanation-info
            h4
              | 解説
            .back-grey
              - if @app.explanation.present?
                #marked-text
                  = @app.explanation
              - else
                p
                  | 解説は投稿されていません。
    .col-sm-2
      = render 'learnings/learning_linkbar', app: @app, learning: @learning

app/views/apps/hidden.html.slim
.container
  .row.border-box
    .col-md-3.border-space
      ul.edit-link
        li
          = link_to "基本情報を編集", edit_app_path(@app)
        li
          = link_to "ヒントを追加・編集", hint_edit_app_path(@app)
        li
          = link_to "解説を追加・編集", explanation_edit_app_path(@app)
        li
          | アプリを非公開にする
    .col-md-9.border-left.border-space
      .edit-app-title
        h2
          = @app.title
      #app-hidden.confirm-message
        p
          | この投稿アプリを一覧ページから非表示に変更します。
          br
          | 非公開にすると、現在学習中のユーザーを除き、一般ユーザーは
          br
          | 一覧ページからこのアプリを閲覧できなくなります。
          br
          | 一度非公開にしたアプリは、元の状態に戻すことはできません。
          br
          br
          | 本当にこのアプリを非公開にしてもよろしいですか？
        = link_to "アプリの公開を継続", app_path(@app), class: "btn btn-primary"
        = link_to "アプリの公開を停止", cancel_app_path(@app), method: :patch, class: "btn btn-danger", "data-confirm" => "アプリを非公開にしてもよろしいですか？"

app/views/apps/hint_edit.html.slim
.marked-wrapper
  span
    = link_to "基本情報編集ページに戻る", edit_app_path(@app), class: "btn btn-default"
  h2
    = @app.title
  h4
    | ヒント編集
  = form_with(model: @app, url: add_update_app_path) do |f|
    .marked-form
      .row
        .col-md-6
          h5
            | 記入欄（マークダウン記法で記述できます）
          .field
            #editor
              = f.text_area :hint, class: "textarea-form form-control", style: "min-height: 480px"
        .col-md-6
          h5
            | プレビュー
          #marked-area
    = f.submit "更新する", class: "btn btn-original"

app/views/apps/index.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li.active
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane.active
            = render 'langs/lang_index', langs: @langs
          #tag-tab.tab-pane
            = render 'tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li.active
            = link_to "新着順", apps_path(q: request.params[:q])
          li
            = link_to "評価順", rate_index_apps_path(q: request.params[:q])
          li
            = link_to "人気順", popular_index_apps_path(q: request.params[:q])
        = render 'app_index', apps: @apps

app/views/apps/new.html.slim
.container
  .row.border-box.top-bottom-space
    .app-form
      = form_with(model: @app, url: confirm_apps_path, local: true) do |f|
        = render 'layouts/error_messages', model: @app
        .field.new-app-form
          = f.label :title, "アプリケーション名"
          = f.text_field :title, class: "form-control"
        .field.new-app-form
          = f.label :lang_id, "開発言語"
          = f.collection_select :lang_id, Lang.all, :id, :name, { include_blank: "選択してください" }, { class: "form-control" }
          p
            | 最もメインで使用した言語を選択してください。
        .field.new-app-form
          = f.label :overview, "アプリケーションの概要"
          = f.text_area :overview, class: "form-control"
        .field.new-app-form
          = f.label :app_url, "アプリケーションURL"
          = f.text_area :app_url, class: "form-control mini-height"
        .field.new-app-form
          = f.label :repo_url, "リポジトリURL"
          = f.text_area :repo_url, class: "form-control mini-height"
        .field.new-app-form
          = f.label :function, "機能"
          = f.text_area :function, class: "form-control"
        .field.new-app-form
          = f.label :target, "対象者"
          = f.text_area :target, class: "form-control mini-height"
        .field.new-app-form
          = f.label :tag_list, "タグ付け"
          ul#app-tags.form-control
          p
            | 複数入力が可能です。
        .actions.text-center
          = f.submit "確認ページへ進む", class: "btn btn-center btn-original"

app/views/apps/popular_index.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li.active
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane.active
            = render 'langs/lang_index', langs: @langs
          #tag-tab.tab-pane
            = render 'tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li
            = link_to "新着順", apps_path(q: request.params[:q])
          li
            = link_to "評価順", rate_index_apps_path(q: request.params[:q])
          li.active
            = link_to "人気順", popular_index_apps_path(q: request.params[:q])
        = render 'app_index', apps: @apps

app/views/apps/popular_tag.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li.active
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane
            = render 'langs/lang_index', langs: @langs
          #tag-tab.tab-pane.active
            = render 'tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li
            = link_to "新着順", tag_apps_path(tag_name: params[:tag_name])
          li
            = link_to "評価順", rate_tag_apps_path(tag_name: params[:tag_name])
          li.active
            = link_to "人気順", popular_tag_apps_path(tag_name: params[:tag_name])
        = render 'apps/app_index', apps: @apps

app/views/apps/rate_index.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li.active
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane.active
            = render 'langs/lang_index', langs: @langs
          #tag-tab.tab-pane
            = render 'tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li
            = link_to "新着順", apps_path(q: request.params[:q])
          li.active
            = link_to "評価順", rate_index_apps_path(q: request.params[:q])
          li
            = link_to "人気順", popular_index_apps_path(q: request.params[:q])
        = render 'app_index', apps: @apps

app/views/apps/rate_tag.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li.active
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane
            = render 'langs/lang_index', langs: @langs
          #tag-tab.tab-pane.active
            = render 'tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li
            = link_to "新着順", tag_apps_path(tag_name: params[:tag_name])
          li.active
            = link_to "評価順", rate_tag_apps_path(tag_name: params[:tag_name])
          li
            = link_to "人気順", popular_tag_apps_path(tag_name: params[:tag_name])
        = render 'apps/app_index', apps: @apps

app/views/apps/show.html.slim
.container
  .row
    .col-sm-10
      .app-show-box.border-space
        article.app-info
          = render 'app_info_top', app: @app
          section.app-contents
            h3
              | 概要
            p
              = @app.overview
          section.app-contents
            h3
              | アプリケーションURL
            = link_to @app.app_url, @app.app_url, target: :_blank, class: "URL"
          section.app-contents
            h3
              | リモートリポジトリURL
            = link_to @app.repo_url, @app.repo_url, target: :_blank
          section.app-contents
            h3
              | 機能一覧
            p
              = @app.function
          section.app-contents
            h3
              | 対象者
            p
              = @app.target
          - if user_signed_in?
            - unless @app.user == current_user || Learning.find_by(user_id: current_user.id, app_id: @app.id) || admin_signed_in?
              #make-app
                = link_to "このアプリケーションを作成する", app_learnings_path(@app), method: :post, class: "btn-lg btn-primary"
    .col-sm-2
      = render 'learnings/learning_linkbar', app: @app, learning: @learning

app/views/apps/tag.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li.active
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane
            = render 'langs/lang_index', langs: @langs
          #tag-tab.tab-pane.active
            = render 'tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li.active
            = link_to "新着順", tag_apps_path(tag_name: params[:tag_name])
          li
            = link_to "評価順", rate_tag_apps_path(tag_name: params[:tag_name])
          li
            = link_to "人気順", popular_tag_apps_path(tag_name: params[:tag_name])
        = render 'apps/app_index', apps: @apps