config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'about' => 'home#about'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get :quit
      patch :cancel
      get :following
      get :followers
      get :learnings
      get :stocks
    end
    resource :relationships, only: [:create, :destroy]
    resources :notifications, only: :index do
      delete :destroy_all, on: :collection
    end
  end

  resources :apps, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      post :confirm
      get :rate_index
      get :popular_index
      get :tag
      get :rate_tag
      get :popular_tag
    end
    member do
      get :hint
      get :explanation
      get :hint_edit
      get :explanation_edit
      patch :add_update
      get :hidden
      patch :cancel
    end
    resources :learnings, only: [:create, :show, :edit, :update]
    resources :questions, only: [:index, :create]
    resources :reviews, only: [:index, :create]
    resource :stocks, only: [:create, :destroy]
  end

  resources :langs, only: :show do
    member do
      get :rate_show
      get :popular_show
    end
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
    post 'admin/guest_sign_in' => 'admins/sessions#new_guest'
  end

  namespace :admin do
    root 'dashboards#index'
    resources :langs, only: [:index, :show, :create, :update, :destroy]
    resources :users, only: :index do
      patch :cancel, on: :member
    end
    resources :apps, only: :index do
      patch :cancel, on: :member
    end
  end
end

app/models/lang.rb
class Lang < ApplicationRecord
  attachment :lang_image
  has_many :apps
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/langs_controller.rb
class Admin::LangsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_lang, only: [:show, :update, :destroy]

  def set_lang
    @lang = Lang.find(params[:id])
  end

  def index
    @lang = Lang.new
    @langs = Lang.all
    @apps = App.where(status: true)
  end

  def create
    @lang = Lang.new(lang_params)
    if @lang.save
      flash[:success] = "新しい開発言語を登録しました。"
      redirect_to admin_lang_path(@lang)
    else
      @langs = Lang.all
      @apps = App.where(status: true)
      render 'index'
    end
  end

  def show
    @langs = Lang.all
    @apps = App.where(status: true)
  end

  def update
    if @lang.update(lang_params)
      flash[:success] = "開発言語名を更新しました。"
      redirect_back(fallback_location: admin_root_path)
    else
      render 'show'
    end
  end

  def destroy
    @lang.destroy
    flash[:alert] = "登録済みの開発言語を削除しました。"
    redirect_to admin_langs_path
  end

  private

  def lang_params
    params.require(:lang).permit(:name, :lang_image)
  end
end

app/controllers/langs_controller.rb
class LangsController < ApplicationController
  before_action :set_method

  def set_method
    @langs = Lang.all
    @lang = Lang.find(params[:id])
    @apps = @lang.apps.where(status: true).includes(:user, :reviews, :taggings)
    @apps.each do |app|
      app.score = app.average_rate
    end
  end

  def show
    @apps = @apps.page(params[:page]).reverse_order
  end

  def rate_show
    @apps = @apps.sort_by { |app| app.score.to_f }.reverse
    @apps = Kaminari.paginate_array(@apps).page(params[:page])
  end

  def popular_show
    @apps = @apps.sort_by { |app| app.learnings.count }.reverse
    @apps = Kaminari.paginate_array(@apps).page(params[:page])
  end
end

app/views/langs/_lang_index.html.slim
ul#lang-index
  - langs.each do |lang|
    = link_to lang_path(lang) do
      li.btn.btn-default.current-lang
        p
          = lang.name
          span
            | （
            = lang.apps.pluck(:status).count(true)
            | ）

app/views/langs/popular_show.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li.active
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane.active
            = render 'lang_index', langs: @langs
          #tag-tab.tab-pane
            = render 'apps/tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li
            = link_to "新着順", lang_path(@lang)
          li
            = link_to "評価順", rate_show_lang_path(@lang)
          li.active
            = link_to "人気順", popular_show_lang_path(@lang)
        = render 'apps/app_index', apps: @apps

app/views/langs/rate_show.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li.active
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane.active
            = render 'lang_index', langs: @langs
          #tag-tab.tab-pane
            = render 'apps/tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li
            = link_to "新着順", lang_path(@lang)
          li.active
            = link_to "評価順", rate_show_lang_path(@lang)
          li
            = link_to "人気順", popular_show_lang_path(@lang)
        = render 'apps/app_index', apps: @apps

app/views/langs/show.html.slim
.container
  .row
    .col-sm-3.sidebar
      .category-bar
        ul.category-menu.nav.nav-tabs
          li.active
            = link_to "言語別", "#lang-tab", data: { toggle: "tab"}
          li
            = link_to "タグ別", "#tag-tab", data: { toggle: "tab"}
        .tab-content.category-contents
          #lang-tab.tab-pane.active
            = render 'lang_index', langs: @langs
          #tag-tab.tab-pane
            = render 'apps/tag_index'
      = render 'users/user_sidebar', user: current_user
    .col-sm-9
      .app-index.back-white
        ul.nav.nav-tabs
          li.active
            = link_to "新着順", lang_path(@lang)
          li
            = link_to "評価順", rate_show_lang_path(@lang)
          li
            = link_to "人気順", popular_show_lang_path(@lang)
        = render 'apps/app_index', apps: @apps